module.exports = [' Chemistry',
                  ' Math',
                  ' English',
                  ' Art',
                  ' Biology',
                  ' Physics',
                  ' Engineering',
                  ' Music',
                  ' Social Sciences',
                  ' Transportation',
                  ' Energy',
                  ' Health Care',
                  ' Internet/Web',
                  ' Media',
                  ' Robotics',
                  ' Nature',
                  ' Communication',
                  ' Literacy',
                  ' Space',
                  ' Entertainment',
                  ' Commerce '];

